version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2
      docker: 20
    commands:
      - echo Installing Bundler and other dependencies
      - gem install bundler
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
  build:
    commands:
      - echo Running tests...
      - docker run --rm $IMAGE_REPO_NAME:$IMAGE_TAG bundle exec rspec
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"rails-container","imageUri":"%s"}]' $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
