# config/sidekiq.yml
---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
:timeout: 30
:queues:
  - [default, 1]
  - [high, 2] # high priority

:scheduler:
  :schedule:
    sync_data:
      cron: '0 0 * * *'   # Runs once per day
      class: SyncTvMazeDataJob
    