services:
  db:
    image: postgres:15
    container_name: local_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: looperinsights_assignment_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: